import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import getDomain from '@/utils/domainName';
import bookInterface from '@/types/bookType';
import { GetStaticProps, InferGetStaticPropsType } from 'next';

/* ---------------------------------------------------------------------------------------------- */
/*                        Initial data fetching to return data from server                        */
/* ---------------------------------------------------------------------------------------------- */
export const getServerSideProps: GetStaticProps = async context => {
  const res = await fetch(`${getDomain()}/api/books`, {
    method: 'GET',
    headers: {
      Authorization: `Perlego${process.env.SECRET_KEY}`,
    },
  });

  const books: bookInterface[] = await res.json();
  return {
    props: { books },
  };
};

export default function BookRecommend({ books }: InferGetStaticPropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Books you may like</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Book Recommendations</h1>
      <ul>
        {books.map((book: bookInterface) => (
          <li key={book._id}>
            <Link href={book.unique_url}>{book.title}</Link>
          </li>
        ))}
      </ul>
    </>
  );
}
