import Head from "next/head";
import Image from "next/image";
import bookInterface from "@/types/bookType";
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import Link from "next/link";


export const getServerSideProps: GetStaticProps = async () => {
  const res = await fetch("http://localhost:3000/api/maxBooks");
  const books: bookInterface[] = await res.json();
  return {
    props: {books},
  }
}


export default function BookRecommend({books} : InferGetStaticPropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Books you may like</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Book Recommendations</h1>
      <ul>
        {books.map((book: bookInterface) => (
          <li key={book._id}>
            <Link href={book.unique_url}>{book.title}</Link>
          </li>
        ))}
      </ul>
    </>
  );
}
